version: 0.2

phases:
    install:
        commands:
            - echo "Installing dependencies..."
            - npm install
    pre_build:
        commands:
            - echo "Linting..."
            - npm run lint
    build:
        commands:
            - echo "Building..."
            - npm run build

artifacts:
    base-directory: 'dist'
    files:
        - '**/*'
